# Generated by Django 6.0.3 on 2026-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DisturbanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("COMTRADE", "COMTRADE"),
                            ("CSV", "CSV"),
                            ("EXCEL", "Excel"),
                            ("PSSE", "PSS/E RAW"),
                        ],
                        default="COMTRADE",
                        max_length=10,
                    ),
                ),
                (
                    "cfg_file",
                    models.FileField(blank=True, null=True, upload_to="comtrade/"),
                ),
                (
                    "dat_file",
                    models.FileField(blank=True, null=True, upload_to="comtrade/"),
                ),
                (
                    "data_file",
                    models.FileField(blank=True, null=True, upload_to="data/"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
