# Generated by Django 6.0.3 on 2026-03-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disturbances", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disturbancerecord",
            name="cfg_file",
        ),
        migrations.RemoveField(
            model_name="disturbancerecord",
            name="dat_file",
        ),
        migrations.RemoveField(
            model_name="disturbancerecord",
            name="data_file",
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="auxiliary_file",
            field=models.FileField(
                blank=True, null=True, upload_to="disturbances/auxiliary/"
            ),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="file_size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="primary_file",
            field=models.FileField(
                blank=True, null=True, upload_to="disturbances/primary/"
            ),
        ),
    ]
