# Generated by Django 6.0.3 on 2026-03-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disturbances", "0002_remove_disturbancerecord_cfg_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disturbancerecord",
            name="auxiliary_file",
        ),
        migrations.RemoveField(
            model_name="disturbancerecord",
            name="primary_file",
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="data_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
