# Generated by Django 6.0.3 on 2026-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disturbances", "0003_remove_disturbancerecord_auxiliary_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="channel_config",
            field=models.JSONField(
                blank=True,
                help_text="User-side overrides: {channel_name: {label, color, scale, unit, visible}}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="nominal_frequency",
            field=models.FloatField(
                default=50.0, help_text="Nominal system frequency (50 or 60 Hz)."
            ),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="sample_rate",
            field=models.FloatField(
                blank=True, help_text="Sampling rate in Hz.", null=True
            ),
        ),
        migrations.AddField(
            model_name="disturbancerecord",
            name="trigger_time",
            field=models.FloatField(
                blank=True,
                help_text="Seconds from record start to trigger event. Frontend centers time axis at this point.",
                null=True,
            ),
        ),
    ]
